d_vars = {
    'var1': {
        'cod': 'CONTROL',
        'unid': '',
        'file': 'PLANT',
        'lims': (),
        'ing': True,
        'egr': False
    },
    'var2': {
        'cod': 'EOP',
        'unid': 'mm/d',
        'file': 'PLANT',
        'lims': (),
        'ing' :  True,
        'egr' : False
    },
    'var3' : {
        'cod' : 'HARVFRAC',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing' : True,
        'egr' : False
    },
    'var4' : {
        'cod' : 'ISWITCH',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var5' : {
        'cod' : 'NH4(L)',
        'unid' : 'microgram(N)/g(Soil)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var6' : {
        'cod': 'NO3(L)',
        'unid' : 'microgram(N)/g (Soil)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var7' : {
        'cod': 'SOILPROP',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False
    },
    'var8' : {
        'cod' : 'ST(L)',
        'unid' : 'degree C',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False
    },
    'var9' : {
        'cod' : 'SW(L)',
        'unid' : 'cm3(water)/cm3(soil)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var10' : {
        'cod' : 'TRWUP',
        'unid' : 'cm/day',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var11' : {
        'cod' : 'WEATHER',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var12' : {
        'cod': 'YREND',
        'unid' : 'YYYYDDD',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var13' : {
        'cod' : 'YRPLT',
        'unid' : 'YYYYDDD',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var14' : {
        'cod' : 'CANHT',
        'unid' : 'm',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var15' : {
        'cod' : 'EORATIO',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '0-6',
        'ing' : False,
        'egr' : True,
    },
    'var16' : {
        'cod': 'HARVRES',
        'unid' : '',
        'file' : 'PLANT',
        'lims': '',
        'ing' : False,
        'egr' : True,
    },
    'var17' : {
        'cod' : 'KSEVAP',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var18' : {
        'cod' : 'KTRANS',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var19': {
        'cod': 'MDATE',
        'unid': '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var20' : {
        'cod' : 'NSTRES',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : (0,1),
        'ing' : False,
        'egr' : True,
    },
    'var21': {
        'cod' : 'PORMIN',
        'unid' : 'cm3/cm3',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var22' : {
        'cod': 'RLV(L)',
        'unid': 'cm(root)\ cm3(soil)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var23' : {
        'cod': 'RWUMX',
        'unid': 'cm3(water)/cm(root)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var24' : {
        'cod': 'SENESCE',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var25' : {
        'cod': 'STGDOY(I)',
        'unid' : 'YYYYDDD',
        'file': 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var26' : {
        'cod' : 'UNH4(L)',
        'unid' : 'kg(N)/ha-d',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var27' : {
        'cod' : 'UNO3(L)',
        'unid' : 'kg(N)/ha-d',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var28' : {
        'cod' : 'XHLAI',
        'unid' : 'm2(leaf)/m2(ground)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var30' : {
        'cod' : 'XLAI',
        'unid' : 'm2(leaf)/m2(ground)',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : False,
        'egr' : True,
    },
    'var31' : {
        'cod' : 'FLOODWAT',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var32' : {
        'cod' : 'SNOW',
        'unid' : 'mm',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr' : False,
    },
    'var33' : {
        'cod' : 'SRFTEMP',
        'unid' : 'degree C',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : True,
        'egr': False,
    },
    'var34' : {
        'cod' : 'FSLFW',
        'unid' : 'l/day',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var35' : {
        'cod' : 'FSLFN',
        'unid' : 'l/day',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var36' : {
        'cod' : 'SDSZ',
        'unid' : 'Mg/seed',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var37' : {
        'cod' : 'RSGR',
        'unid' : '',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var38' : {
        'cod' : 'RSGRT',
        'unid' : 'days',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var39' : {
        'cod' : 'CARBOT',
        'unid' : 'days',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    },
    'var40' : {
        'cod' : 'DSGT',
        'unid' : 'days',
        'file' : 'PLANT',
        'lims' : '',
        'ing' : '',
        'egr' : '',
    }
}



