d_vars = {
    'Control ': {
        'cod': 'CONTROL',
        'unid': '',
        'file': 'PLANT',
        'lims': (),
        'ing': True,
        'egr': False
    },
    'Potential plant transpiration rate': {
        'cod': 'EOP',
        'unid': 'mm/d',
        'file': 'PLANT',
        'lims': (),
        'ing': True,
        'egr': False
    },
    'fraction of yield harvested and by product harvested': {
        'cod': 'HARVFRAC',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False
    },
    'Switches which control flow of execution for model': {
        'cod': 'ISWITCH',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Ammonium': {
        'cod': 'NH4(L)',
        'unid': 'microgram(N)/g(Soil)',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Nitrate': {
        'cod': 'NO3(L)',
        'unid': 'microgram(N)/g (Soil)',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'soil properties': {
        'cod': 'SOILPROP',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False
    },
    'Soil temperature': {
        'cod': 'ST(L)',
        'unid': 'degree C',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False
    },
    'Volumetric soil water content': {
        'cod': 'SW(L)',
        'unid': 'cm3(water)/cm3(soil)',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Potential daily root uptake': {
        'cod': 'TRWUP',
        'unid': 'cm/day',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Weather data': {
        'cod': 'WEATHER',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'harvest date': {
        'cod': 'YREND',
        'unid': 'YYYYDDD',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Planting date': {
        'cod': 'YRPLT',
        'unid': 'YYYYDDD',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Canopy height': {
        'cod': 'CANHT',
        'unid': 'm',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Ratio of increase in evapotranspiration': {
        'cod': 'EORATIO',
        'unid': '',
        'file': 'PLANT',
        'lims': '0-6',
        'ing': False,
        'egr': True,
    },
    'Harvest residue amounts': {
        'cod': 'HARVRES',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Light extinction coefficient for soil evaporation': {
        'cod': 'KSEVAP',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Light extinction coefficient for soil transpiration': {
        'cod': 'KTRANS',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Harvest maturity date': {
        'cod': 'MDATE',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Nitrogen stress factor': {
        'cod': 'NSTRES',
        'unid': '',
        'file': 'PLANT',
        'lims': (0, 1),
        'ing': False,
        'egr': True,
    },
    'Pore spass requirement for oxygen supply to roots': {
        'cod': 'PORMIN',
        'unid': 'cm3/cm3',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Root length density': {
        'cod': 'RLV(L)',
        'unid': 'cm(root)\ cm3(soil)',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Maximum water uptake per unit root length': {
        'cod': 'RWUMX',
        'unid': 'cm3(water)/cm(root)',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Data about daily senesced plant matter': {
        'cod': 'SENESCE',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Day when plant stage 1 occured': {
        'cod': 'STGDOY(I)',
        'unid': 'YYYYDDD',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Rate of root uptake of NH4': {
        'cod': 'UNH4(L)',
        'unid': 'kg(N)/ha-d',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Rate of root uptake of NO3': {
        'cod': 'UNO3(L)',
        'unid': 'kg(N)/ha-d',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Healthy leaf area index': {
        'cod': 'XHLAI',
        'unid': 'm2(leaf)/m2(ground)',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Leaf area per unit ground area': {
        'cod': 'XLAI',
        'unid': 'm2(leaf)/m2(ground)',
        'file': 'PLANT',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Information related to bund management': {
        'cod': 'FLOODWAT',
        'unid': '',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Snow accumulation': {
        'cod': 'SNOW',
        'unid': 'mm',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Soil surface temperature': {
        'cod': 'SRFTEMP',
        'unid': 'degree C',
        'file': 'PLANT',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Daily fraction of leaf area senesced under 100% water stress': {
        'cod': 'FSLFW',
        'unid': 'l/day',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Daily fraction of leaf area senesced under 100% nitrogen stress': {
        'cod': 'FSLFN',
        'unid': 'l/day',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Maximum potential seed size': {
        'cod': 'SDSZ',
        'unid': 'Mg/seed',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Relative seed growth rate': {
        'cod': 'RSGR',
        'unid': '',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    ' consecutive days relative seed growth rate is below RSGR before early maturity ': {
        'cod': 'RSGRT',
        'unid': 'days',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Number of consecutive days that daily plant growth rate is below 0.001 g/plant before plant growth is terminated due to stress': {
        'cod': 'CARBOT',
        'unid': 'days',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Maximum days from sowing to germination before seed dies ': {
        'cod': 'DSGT',
        'unid': 'days',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Growing degree days between germination and emergenc': {
        'cod': 'DGET',
        'unid': 'GDD',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Minimum available soil water required for seed germination ': {
        'cod': 'SWCG',
        'unid': 'cm3/cm3',
        'file': 'PLANT',
        'lims': 'Maize species coefficient',
        'ing': '',
        'egr': '',
    },
    'Stem weight at emergence': {
        'cod': 'STMWTE',
        'unid': 'G/plant',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Root weight at emergence': {
        'cod': 'RTWTE',
        'unid': 'G/plant',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Leaf weight at emergence': {
        'cod': 'LFWTE',
        'unid': 'G/plant',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Carbohydrate reserve in seed at emergence': {
        'cod': 'SEEDRVE',
        'unid': 'G/plant',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Leaf number at emergence': {
        'cod': 'LEAFNOE',
        'unid': '#/plant',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Plant top minimum N concentration': {
        'cod': 'TMNC',
        'unid': 'g N/g dry matter',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Nitrogen content in above ground biomass at emergence': {
        'cod': 'TANCE',
        'unid': 'g N/g dry matter',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Root critical nitrogen concentration': {
        'cod': 'RCNP',
        'unid': 'g N/g dry matter',
        'file': 'Maize species coefficient',
        'lims': (0, 1),
        'ing': '',
        'egr': '',
    },
    'Root N content at emergence': {
        'cod': 'RANCE',
        'unid': 'g N/g root',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Minimum volume for supplying oxygen to roots': {
        'cod': 'PORM',
        'unid': '',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Maximum root water uptake per unit length of root': {
        'cod': 'RWMX',
        'unid': 'cm3 water/cm root',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Root length to weight ratio': {
        'cod': 'RLWR',
        'unid': 'cm/g',
        'file': 'Maize species coefficient',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Threshold soil water content for reducing leaf expansion ': {
        'cod': 'RWUEP1',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    'Soil water change drainage': {
        'info': 'Change in soil water content due to drainage',
        'cod': 'SWDELTS(L)',
        'unid': 'cm3 water/ cm3 soil',
        'file': 'Soil',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Soil water change upflow': {
        'info': 'Change in soil water content due to evaporation and/or upward flow',
        'cod': 'SWDELTU(L)',
        'unid': '',
        'file': 'Soil',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Water available for infiltration': {
        'cod': 'WINF',
        'unid': 'mm/d',
        'file': 'Soil',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Soil water change root uptake': {
        'info': 'Change in soil water content due to root water uptake in layer L',
        'cod': 'SWDELTX(L)',
        'unid': 'cm3 (water)/cm3 (soil)',
        'file': 'Soil water',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Irrigation amount for today': {
        'cod': 'IRRAMT',
        'unid': 'mm/d',
        'file': 'Management',
        'lims': '',
        'ing': False,
        'egr': True,
    },
    'Planting/transplanting': {
        'cod': 'IPLTI',
        'unid': '',
        'file': 'Management',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Irrigation and Water management': {
        'cod': 'IIRRI',
        'unid': '',
        'file': 'Management',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    'Fertilization': {
        'cod': 'IFERI',
        'unid': '',
        'file': 'Management',
        'lims': '',
        'ing': True,
        'egr': False,
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
    '': {
        'cod': '',
        'unid': '',
        'file': '',
        'lims': '',
        'ing': '',
        'egr': '',
    },
}
